/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileSearcher.java
 *
 * Created on 01.12.2009, 13:32:16
 */

package htw;

import java.io.File;
import java.util.ArrayList;
import java.util.regex.PatternSyntaxException;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import java.awt.event.MouseEvent;

/**
 *
 * @author Tobbe
 */
public class FileSearcher extends JFrame {

	// Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup buttonGroup1;
    private JButton btnSearch;
    private JRadioButton rbSearchFileName;
    private JRadioButton rbSearchFileContent;
    private JScrollPane spResult;
    private JTable jTable1;
    private JTextField tfText;
    // End of variables declaration//GEN-END:variables
	
    private File directory;

    /** Creates new form FileSearcher */
    public FileSearcher(File directory) {
        initComponents();
        this.directory = directory;
        this.setTitle("Suche: " + directory.getAbsolutePath());

        jTable1.addMouseListener(new htw.controls.MouseAdapterExtended() {
            @Override
            public void mouseDoubleClicked(MouseEvent e) {
                tableMouseDoubleClicked(e);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        spResult = new JScrollPane();
        jTable1 = new JTable();
        tfText = new JTextField();
        rbSearchFileName = new JRadioButton();
        rbSearchFileContent = new JRadioButton();
        btnSearch = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Datei"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spResult.setViewportView(jTable1);

        buttonGroup1.add(rbSearchFileName);
        rbSearchFileName.setSelected(true);
        rbSearchFileName.setText("Nach Dateinamen suchen");

        buttonGroup1.add(rbSearchFileContent);
        rbSearchFileContent.setText("Nach Dateiinhalt suchen");

        btnSearch.setText("Suchen");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbSearchFileName)
                        .addGap(18, 18, 18)
                        .addComponent(rbSearchFileContent))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfText, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)))
                .addContainerGap())
            .addComponent(spResult, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSearchFileName)
                    .addComponent(rbSearchFileContent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spResult, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clearTable();

        String pattern = tfText.getText();
        pattern = pattern.replace(".", "\\.");
        pattern = pattern.replace("*", ".*");

        try {
            ArrayList<File> result;
            if (rbSearchFileName.isSelected()) {
            	result = FileSystem.searchForFileName(directory, pattern);
            } else {
            	result = FileSystem.searchForTextInFile(directory, pattern);
            }
            if (result.size() > 0) {
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                for (File f : result) {
                    model.addRow(new Object[] { f.getAbsolutePath() });
                }
            }
        }
        catch (PatternSyntaxException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "IO Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearTable() {
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        while (model.getRowCount() > 0)
            model.removeRow(0);
    }

        // <editor-fold defaultstate="collapsed" desc="DoubleClick event">
    private void tableMouseDoubleClicked(MouseEvent e) {
        int row = jTable1.rowAtPoint(e.getPoint());
        String file = jTable1.getModel().getValueAt(row, 0).toString();
        if (file.endsWith(".txt")) {
        	new FileView(file);
        }            
    }
    // </editor-fold>
}
